---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: Europe/Amsterdam
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Akoten"
keywords:    "Akoten, webistes, development, django, ansible, python, scala, play, ionic, angularjs, angular, coding, amsterdam, business, startup, design, apps"
description: "Akoten - Advising, Building, Collaborating or just good advice."
source_link: "https://github.com/Akoten/akoten.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/favicon.ico"
use_piwik: "yes"


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'